/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ChatHeader: typeof import('./src/components/ChatHeader.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatInterface: typeof import('./src/components/ChatInterface.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ChatMessages: typeof import('./src/components/ChatMessages.vue')['default']
    ClaimTypeSelector: typeof import('./src/components/ClaimTypeSelector.vue')['default']
    CountySelector: typeof import('./src/components/CountySelector.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    PredictionCards: typeof import('./src/components/PredictionCards.vue')['default']
    PredictionChart: typeof import('./src/components/PredictionChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarFilters: typeof import('./src/components/SidebarFilters.vue')['default']
  }
}
